typo and modify content
rust-tw/book-tw pull request #52
Opened 2021-04-16 14:43 UTC by z-Wind

並不過這能為 -> 這只是能為
Trunk -> Thunk
系安在 -> 現在
不會任何 -> 不會認為
流來器 -> 瀏覽器
整本輸 -> 整本書
不允許你使用 `fn` 函式指標 -> 不允許你使用 `Fn` 特徵
(原文也是錯的，fn 應可當回傳型別，且範例也是 `Fn` 特徵)

2021-04-16 14:58 UTC, CYBAI approved these changes
感謝貢獻！

overall LGTM! only one nit!

2021-04-16 14:58 UTC, CYBAI commented on src/appendix-07-nightly-rust.md
> +以下是開發與發佈過程是如何進行的範例：讓我們假設 Rust 團隊正在準備發佈 Rust 1.5。這在 2015 年十二月就發佈了，這只是能為我們提供較真實的版本數字。其中有一個新功能會加入 Rust 並在 `master` 分支新增一個 commit。每個晚上 Rust 都會產生新的夜版版本，然後每到天亮就會發佈，而這些發佈均由發佈基礎設施自動產生。所以隨著時間過去，我們每晚都會有一個發佈像這樣
nit: IMO, 可能說「只是為」會比較通順？

```diff
- 這只是能為我們提供較真實的版本數字
+ 這只是為我們提供較真實的版本數字
```

2021-04-16 14:58 UTC, weihanglo requested changes

2021-04-16 14:58 UTC, weihanglo commented on src/ch19-05-advanced-functions-and-closures.md
> +閉包是用特徵來表示，言下之意是你不能直接回傳一個閉包。大多數的情況，當你想回傳一個特徵時，可以改回傳有實作該特徵的具體型別。但你並無法對閉包這樣做，因為它們根本沒有可供回傳的具體型別，比方說不允許你使用 `Fn` 特徵作為回傳型別。
https://github.com/rust-lang/book/blob/d44317c/src/ch19-05-advanced-functions-and-closures.md#returning-closures

原文是「you’re not allowed to use the function pointer `fn` as a return type, for example.」，應該沒錯喔。

2021-04-16 14:58 UTC, weihanglo commented on src/appendix-07-nightly-rust.md
> +這就叫「火車模型（train model）」，因為每隔六週就會有個發佈「駛離車站」，但其仍需要穿梭過測試版通道，才能抵達穩定版發佈。
感覺連「隔」都去掉會更通順？

2021-04-16 14:58 UTC, weihanglo commented on src/appendix-07-nightly-rust.md
> +以下是開發與發佈過程是如何進行的範例：讓我們假設 Rust 團隊正在準備發佈 Rust 1.5。這在 2015 年十二月就發佈了，這只是能為我們提供較真實的版本數字。其中有一個新功能會加入 Rust 並在 `master` 分支新增一個 commit。每個晚上 Rust 都會產生新的夜版版本，然後每到天亮就會發佈，而這些發佈均由發佈基礎設施自動產生。所以隨著時間過去，我們每晚都會有一個發佈像這樣
```suggestion
以下是開發與發佈過程是如何進行的範例：讓我們假設 Rust 團隊正在準備發佈 Rust 1.5。這版本早在 2015 年十二月就發佈，做此假設只是為我們提供較真實的版本數字。其中有一個新功能會加入 Rust 並在 `master` 分支新增一個 commit。每個晚上 Rust 都會產生新的夜版版本，然後每到天亮就會發佈，而這些發佈均由發佈基礎設施自動產生。所以隨著時間過去，我們每晚都會有一個發佈像這樣進行：
```

2021-04-16 14:59 UTC, weihanglo commented
感謝 @z-Wind 協助校稿！！

2021-04-16 15:04 UTC, weihanglo commented on src/ch19-05-advanced-functions-and-closures.md
> +閉包是用特徵來表示，言下之意是你不能直接回傳一個閉包。大多數的情況，當你想回傳一個特徵時，可以改回傳有實作該特徵的具體型別。但你並無法對閉包這樣做，因為它們根本沒有可供回傳的具體型別，比方說不允許你使用 `Fn` 特徵作為回傳型別。
原來你的意思是原文也是錯的啊...瞭解 XDD

2021-04-16 15:07 UTC, weihanglo approved these changes
LGTM
大感謝！

2021-04-16 16:11 UTC, merged

2021-04-17 02:07 UTC, z-Wind commented on src/appendix-07-nightly-rust.md
> +以下是開發與發佈過程是如何進行的範例：讓我們假設 Rust 團隊正在準備發佈 Rust 1.5。這在 2015 年十二月就發佈了，這只是能為我們提供較真實的版本數字。其中有一個新功能會加入 Rust 並在 `master` 分支新增一個 commit。每個晚上 Rust 都會產生新的夜版版本，然後每到天亮就會發佈，而這些發佈均由發佈基礎設施自動產生。所以隨著時間過去，我們每晚都會有一個發佈像這樣
抱歉，我對 PR 流程不熟，按錯 Resolve conversation
你的建議比我的好很多，當初我也想很久，但怎麼改都不通順

2021-04-17 02:07 UTC, z-Wind commented on src/appendix-07-nightly-rust.md
> +這就叫「火車模型（train model）」，因為每隔六週就會有個發佈「駛離車站」，但其仍需要穿梭過測試版通道，才能抵達穩定版發佈。
有想過把「隔」去掉，但總覺得少了點味道
像是今天發佈了，再來就是每隔六週發佈
若改成每六週，有一種不知道起點的感覺